name: Server CI Build

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - '**'  # Triggers on all branches for pull requests
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16' # Specify the Node.js version you are using

      - name: Install dependencies
        run: npm install
        working-directory: server

      - name: Run Prisma migrations
        run: npx prisma migrate deploy
        working-directory: server

      - name: Build server
        run: npm run build
        working-directory: server

      - name: Test server
        run: npm test
        working-directory: server
